export { detectStreakRisk } from './detect-streak-risk'
export { detectStaleProjects } from './detect-stale-projects'
export { detectBudgetWarn } from './detect-budget-warn'
export { detectSleepDrop } from './detect-sleep-drop'
export { detectEnergyPattern } from './detect-energy-pattern'
export { detectDecisionReview } from './detect-decision-review'
export { detectAchievements } from './detect-achievements'
export { detectVelocity } from './detect-velocity'
export { detectThreats } from './detect-threats'
export type { Insight, InsightType, InsightCategory, InsightSeverity, DetectorContext, Detector } from './types'
export { MS_PER_DAY, MS_PER_WEEK, getMonthlySpending, getSleepTrend, getProjectVelocity } from './utils'
