export { buildTaskContext } from './task-context'
export { buildGoalContext } from './goal-context'
export { buildProjectContext } from './project-context'
export { buildHabitContext } from './habit-context'
export { buildGlobalContext } from './global-context'
export { buildWealthContext, toWealthBrief, emptyWealthBrief, tierDrift, TIERS } from './wealth-context'
export type { WealthBrief, WealthBriefInput, BriefHolding, BriefLp, BriefLending, BriefWindow } from './wealth-context'
export { DATA_RULES, UNAVAILABLE, EnvelopeBuilder, renderFigure, renderSection, renderDataGaps, formatAge, formatValue, figureState, STALE_AFTER_SECONDS } from './wealth-envelope'
export type { Figure, FigureState, FigureUnit, RenderedFigure, RenderedSection } from './wealth-envelope'
