//! Differential parity for the analytics layer, against the Python oracle.
//!
//! `analytics_corpus.json` is generated by running the REAL `analysis.py` and
//! `pow_mcp/analytics.py` over synthetic portfolios — empty, single-asset, perfectly even,
//! extremely concentrated, LP pairs with and without priced legs, perp-bot collateral,
//! rebalance baskets, lending-only books, wrapper duplicates, dust and whale magnitudes, custom
//! targets, and values engineered to land on a decimal rounding tie. Regenerate with
//! `tests/gen_analytics_corpus.py` (the command is in that file's docstring).
//!
//! The load-bearing test in this file is `a_metric_without_the_data_comes_back_null_with_a_reason`:
//! the honesty envelope is the property most likely to be quietly lost in a port —
//! a `0.0` where Python says "cannot be computed" still type-checks, still serializes, and is
//! wrong in the most expensive possible way. It is asserted against the oracle's exact reason
//! strings, not just against nullness.

use std::collections::BTreeSet;

use serde::Deserialize;

use lyra_analytics::envelope::{
    Confidence, Metric, TokenAmount, emission_dependency, lending_health, liquidation_buffer,
    round_dp,
};
use lyra_analytics::exposure::{
    Concentration, DefiPosition, ExposureRow, NO_EXPOSURE_NOTE, concentration, exposure_map,
    norm_sym,
};
use lyra_analytics::tiers::{
    DriftAction, HARD, Holding, REB_TOL, STABLES, TIER_ORDER, Tier, TierTargets, YIELD_TOKENS,
    classify, rebalance_plan,
};

/// Relative tolerance, with a tiny absolute floor so that a pair of near-zero values (a dust
/// percentage, an empty tier) does not fail on a relative comparison against ~0.
const REL_TOL: f64 = 1e-9;
const ABS_FLOOR: f64 = 1e-12;

fn approx(a: f64, b: f64) -> bool {
    if a == b {
        return true;
    }
    if !a.is_finite() || !b.is_finite() {
        return false;
    }
    let diff = (a - b).abs();
    diff <= ABS_FLOOR || diff <= REL_TOL * a.abs().max(b.abs())
}

fn assert_close(ours: f64, python: f64, what: &str) {
    assert!(
        approx(ours, python),
        "{what}: rust={ours:?} python={python:?} (diff {})",
        (ours - python).abs()
    );
}

fn assert_close_opt(ours: Option<f64>, python: Option<f64>, what: &str) {
    match (ours, python) {
        (None, None) => {}
        (Some(o), Some(p)) => assert_close(o, p, what),
        _ => panic!("{what}: rust={ours:?} python={python:?} — nullability disagrees"),
    }
}

// ---------- corpus shapes ----------

#[derive(Debug, Deserialize)]
struct Corpus {
    tier_order: Vec<String>,
    tier_target_default: TargetsJson,
    reb_tol: f64,
    tier_meta: std::collections::HashMap<String, TierMeta>,
    stables: Vec<String>,
    hard: Vec<String>,
    yield_tokens: Vec<String>,
    no_exposure_note: String,
    rounding: Vec<RoundingCase>,
    norm_sym: Vec<NormCase>,
    classify: Vec<ClassifyCase>,
    envelope: Vec<EnvelopeCase>,
    portfolios: Vec<Portfolio>,
}

#[derive(Debug, Deserialize)]
struct TierMeta {
    rank: String,
    label: String,
    desc: String,
}

#[derive(Debug, Clone, Copy, Deserialize)]
struct TargetsJson {
    reserve: f64,
    store: f64,
    cashflow: f64,
    highrisk: f64,
}

impl From<TargetsJson> for TierTargets {
    fn from(t: TargetsJson) -> Self {
        TierTargets {
            reserve: t.reserve,
            store: t.store,
            cashflow: t.cashflow,
            highrisk: t.highrisk,
        }
    }
}

#[derive(Debug, Deserialize)]
struct RoundingCase {
    value: f64,
    digits: usize,
    rounded: f64,
}

#[derive(Debug, Deserialize)]
struct NormCase {
    symbol: String,
    normalized: String,
}

#[derive(Debug, Deserialize)]
struct ClassifyCase {
    symbol: Option<String>,
    category: Option<String>,
    tier: Tier,
}

#[derive(Debug, Deserialize)]
struct EnvelopeCase {
    kind: String,
    name: String,
    #[serde(default)]
    tokens: Vec<TokenAmount>,
    #[serde(default)]
    rewards: Vec<TokenAmount>,
    #[serde(default)]
    hf: Option<f64>,
    metric: Metric,
    #[serde(default)]
    liquidation_buffer: Option<f64>,
}

impl EnvelopeCase {
    /// Recompute this case with the Rust port.
    fn ours(&self) -> Metric {
        match self.kind.as_str() {
            "emission_dependency" => emission_dependency(&self.tokens, &self.rewards),
            "lending_health" => lending_health(self.hf),
            other => panic!("unknown envelope case kind {other:?}"),
        }
    }
}

#[derive(Debug, Deserialize)]
struct Portfolio {
    name: String,
    holdings: Vec<Holding>,
    targets: Option<TargetsJson>,
    spot: Vec<TokenAmount>,
    defi: Vec<DefiPosition>,
    expected: Expected,
}

#[derive(Debug, Deserialize)]
struct Expected {
    tiers: Vec<Tier>,
    plan: PlanJson,
    exposure: Vec<ExposureRow>,
    concentration: ConcJson,
}

#[derive(Debug, Deserialize)]
struct PlanJson {
    total_usd: f64,
    tolerance_pct: f64,
    tiers: Vec<DriftRowJson>,
}

#[derive(Debug, Deserialize)]
struct DriftRowJson {
    tier: Tier,
    label: String,
    rank: String,
    value_usd: f64,
    now_pct: f64,
    target_pct: f64,
    drift_pct: f64,
    action: DriftAction,
    action_usd: f64,
}

/// Python omits `top_asset` entirely on an empty book, so every field defaults.
#[derive(Debug, Default, Deserialize)]
struct ConcJson {
    #[serde(default)]
    hhi: Option<f64>,
    #[serde(default)]
    top_asset: Option<String>,
    #[serde(default)]
    top_asset_pct: Option<f64>,
    #[serde(default)]
    stablecoin_pct: Option<f64>,
    #[serde(default)]
    note: String,
}

fn load() -> Corpus {
    serde_json::from_str(include_str!("analytics_corpus.json"))
        .expect("analytics_corpus.json should parse")
}

// ---------- constants ----------

#[test]
fn the_ladder_constants_match_python() {
    let c = load();
    assert_eq!(
        c.tier_order,
        TIER_ORDER.iter().map(|t| t.key()).collect::<Vec<_>>()
    );
    assert_close(REB_TOL, c.reb_tol, "REB_TOL");

    let defaults = TierTargets::default();
    for tier in TIER_ORDER {
        let py: TierTargets = c.tier_target_default.into();
        assert_close(
            defaults.get(tier),
            py.get(tier),
            &format!("default target {}", tier.key()),
        );
        let meta = &c.tier_meta[tier.key()];
        assert_eq!(tier.rank(), meta.rank, "rank {}", tier.key());
        assert_eq!(tier.label(), meta.label, "label {}", tier.key());
        assert_eq!(tier.desc(), meta.desc, "desc {}", tier.key());
    }
}

#[test]
fn the_symbol_sets_match_python() {
    let c = load();
    let set = |v: &[&str]| v.iter().map(|s| s.to_string()).collect::<BTreeSet<_>>();
    assert_eq!(set(&STABLES), c.stables.into_iter().collect());
    assert_eq!(set(&HARD), c.hard.into_iter().collect());
    assert_eq!(set(&YIELD_TOKENS), c.yield_tokens.into_iter().collect());
}

// ---------- primitives ----------

#[test]
fn rounding_agrees_with_python_on_every_tie() {
    let c = load();
    assert!(c.rounding.len() > 100, "rounding corpus looks truncated");
    for case in &c.rounding {
        let ours = round_dp(case.value, case.digits);
        assert!(
            ours.to_bits() == case.rounded.to_bits() || approx(ours, case.rounded),
            "round({}, {}): rust={ours:?} python={:?}",
            case.value,
            case.digits,
            case.rounded
        );
    }
}

#[test]
fn symbol_normalization_agrees_with_python() {
    for case in &load().norm_sym {
        assert_eq!(
            norm_sym(&case.symbol),
            case.normalized,
            "norm_sym({:?})",
            case.symbol
        );
    }
}

#[test]
fn tier_classification_agrees_with_python() {
    let c = load();
    assert!(c.classify.len() > 300, "classify corpus looks truncated");
    for case in &c.classify {
        let ours = classify(case.symbol.as_deref(), case.category.as_deref());
        assert_eq!(
            ours, case.tier,
            "classify(symbol={:?}, category={:?})",
            case.symbol, case.category
        );
    }
}

// ---------- the honesty envelope ----------

/// The whole reason this crate is trustworthy. A metric the snapshot cannot support must be
/// `None` **with the oracle's own reason attached** — not `0.0`, not an estimate, not a silently
/// dropped field. `0.0` and "unknown" are indistinguishable downstream, which is exactly how an
/// agent ends up confidently wrong about a book it never actually measured.
#[test]
fn a_metric_without_the_data_comes_back_null_with_a_reason() {
    let c = load();
    let mut checked = 0;
    for case in &c.envelope {
        if case.metric.value.is_some() {
            continue; // computable cases are covered by the agreement test below
        }
        let ours = case.ours();
        assert!(
            ours.is_unavailable(),
            "{}/{}: python says uncomputable but rust produced {:?} — a fabricated number",
            case.kind,
            case.name,
            ours.value
        );
        assert_ne!(
            ours.value,
            Some(0.0),
            "{}/{}: uncomputable must not degrade to 0.0",
            case.kind,
            case.name
        );
        assert_eq!(
            ours.confidence,
            Confidence::Na,
            "{}/{}: uncomputable must carry n/a confidence",
            case.kind,
            case.name
        );
        assert!(
            !ours.data_gaps.is_empty(),
            "{}/{}: null without a reason is worse than no metric at all",
            case.kind,
            case.name
        );
        assert_eq!(
            ours.data_gaps, case.metric.data_gaps,
            "{}/{}: the reason string must match Python exactly",
            case.kind, case.name
        );
        checked += 1;
    }
    assert!(
        checked >= 6,
        "expected the corpus to exercise the null-with-reason path, only saw {checked}"
    );
}

#[test]
fn the_envelope_agrees_with_python_on_every_case() {
    let c = load();
    for case in &c.envelope {
        let ours = case.ours();
        let label = format!("{}/{}", case.kind, case.name);
        assert_close_opt(ours.value, case.metric.value, &format!("{label} value"));
        assert_eq!(ours.unit, case.metric.unit, "{label} unit");
        assert_eq!(
            ours.confidence, case.metric.confidence,
            "{label} confidence"
        );
        assert_eq!(ours.data_gaps, case.metric.data_gaps, "{label} data_gaps");
        assert_eq!(ours.note, case.metric.note, "{label} note");

        if case.kind == "lending_health" {
            assert_close_opt(
                liquidation_buffer(case.hf),
                case.liquidation_buffer,
                &format!("{label} liquidation_buffer"),
            );
        }
    }
}

// ---------- portfolios: tiers, drift, exposure, concentration ----------

#[test]
fn tier_drift_agrees_with_python_on_every_portfolio() {
    let c = load();
    assert!(c.portfolios.len() > 50, "portfolio corpus looks truncated");
    for p in &c.portfolios {
        // classification of each holding, first
        let ours_tiers: Vec<Tier> = p.holdings.iter().map(|h| h.tier()).collect();
        assert_eq!(ours_tiers, p.expected.tiers, "[{}] holding tiers", p.name);

        let targets: Option<TierTargets> = p.targets.map(Into::into);
        let plan = rebalance_plan(&p.holdings, targets.as_ref());
        let want = &p.expected.plan;
        assert_close(
            plan.total_usd,
            want.total_usd,
            &format!("[{}] total", p.name),
        );
        assert_close(
            plan.tolerance_pct,
            want.tolerance_pct,
            &format!("[{}] tolerance", p.name),
        );
        assert_eq!(plan.tiers.len(), want.tiers.len(), "[{}] row count", p.name);
        for (ours, py) in plan.tiers.iter().zip(&want.tiers) {
            let at = format!("[{}] {}", p.name, py.tier.key());
            assert_eq!(ours.tier, py.tier, "{at} tier");
            assert_eq!(ours.label, py.label, "{at} label");
            assert_eq!(ours.rank, py.rank, "{at} rank");
            assert_close(ours.value_usd, py.value_usd, &format!("{at} value_usd"));
            assert_close(ours.now_pct, py.now_pct, &format!("{at} now_pct"));
            assert_close(ours.target_pct, py.target_pct, &format!("{at} target_pct"));
            assert_close(ours.drift_pct, py.drift_pct, &format!("{at} drift_pct"));
            assert_eq!(ours.action, py.action, "{at} action");
            assert_close(ours.action_usd, py.action_usd, &format!("{at} action_usd"));
        }
    }
}

#[test]
fn exposure_unwrap_agrees_with_python_on_every_portfolio() {
    for p in &load().portfolios {
        let ours = exposure_map(&p.spot, &p.defi);
        let want = &p.expected.exposure;
        assert_eq!(
            ours.iter().map(|r| r.asset.as_str()).collect::<Vec<_>>(),
            want.iter().map(|r| r.asset.as_str()).collect::<Vec<_>>(),
            "[{}] exposure assets (and their order)",
            p.name
        );
        for (o, w) in ours.iter().zip(want) {
            assert_close(o.usd, w.usd, &format!("[{}] exposure {}", p.name, w.asset));
        }
    }
}

#[test]
fn concentration_agrees_with_python_on_every_portfolio() {
    for p in &load().portfolios {
        let ours = concentration(&exposure_map(&p.spot, &p.defi));
        let want = &p.expected.concentration;
        assert_close_opt(ours.hhi, want.hhi, &format!("[{}] hhi", p.name));
        assert_eq!(ours.top_asset, want.top_asset, "[{}] top_asset", p.name);
        assert_close_opt(
            ours.top_asset_pct,
            want.top_asset_pct,
            &format!("[{}] top_asset_pct", p.name),
        );
        assert_close_opt(
            ours.stablecoin_pct,
            want.stablecoin_pct,
            &format!("[{}] stablecoin_pct", p.name),
        );
        assert_eq!(ours.note, want.note, "[{}] note", p.name);
    }
}

/// An empty book has no concentration to report. `hhi: 0.0` would claim perfect diversification
/// — the exact opposite of "we cannot tell" — so the null-with-reason rule applies here too.
#[test]
fn hhi_is_null_with_reason_on_an_empty_portfolio() {
    let c = load();
    let empty = c
        .portfolios
        .iter()
        .find(|p| p.name == "empty")
        .expect("corpus should carry an empty portfolio");
    assert!(empty.expected.concentration.hhi.is_none());

    let ours: Concentration = concentration(&[]);
    assert_eq!(ours.hhi, None);
    assert_eq!(ours.top_asset, None);
    assert_eq!(ours.top_asset_pct, None);
    assert_eq!(ours.stablecoin_pct, None);
    assert_eq!(ours.note, NO_EXPOSURE_NOTE);
    assert_eq!(ours.note, c.no_exposure_note, "reason must match Python");

    // A book whose every line is a lending liability also unwraps to nothing.
    let lending = c
        .portfolios
        .iter()
        .find(|p| p.name == "lending_only_has_no_exposure")
        .expect("corpus should carry a lending-only portfolio");
    assert!(exposure_map(&lending.spot, &lending.defi).is_empty());
    assert!(
        concentration(&exposure_map(&lending.spot, &lending.defi))
            .hhi
            .is_none()
    );
}

/// The degenerate ends of the HHI scale, pinned against the oracle: one position is maximal
/// concentration (1.0), *n* equal positions score 1/*n*.
#[test]
fn hhi_hits_its_bounds_on_the_degenerate_portfolios() {
    let c = load();
    let by_name = |name: &str| {
        c.portfolios
            .iter()
            .find(|p| p.name == name)
            .unwrap_or_else(|| panic!("corpus should carry the {name} portfolio"))
    };

    for name in ["single_asset", "single_asset_dust"] {
        let p = by_name(name);
        let ours = concentration(&exposure_map(&p.spot, &p.defi));
        assert_eq!(ours.hhi, Some(1.0), "[{name}] a lone position is maximal");
        assert_eq!(ours.top_asset_pct, Some(100.0));
        assert_close_opt(ours.hhi, p.expected.concentration.hhi, "[single] hhi");
    }

    let even = by_name("perfectly_even_four");
    let ours = concentration(&exposure_map(&even.spot, &even.defi));
    assert_eq!(ours.hhi, Some(0.25), "four equal assets score 1/4");
    assert_eq!(ours.top_asset_pct, Some(25.0));
    assert_close_opt(ours.hhi, even.expected.concentration.hhi, "[even4] hhi");

    let three = by_name("perfectly_even_three");
    let ours = concentration(&exposure_map(&three.spot, &three.defi));
    assert_eq!(ours.hhi, Some(0.333), "three equal assets score ~1/3");
    assert_close_opt(ours.hhi, three.expected.concentration.hhi, "[even3] hhi");

    // ...and the concentrated case sits near the top of the range without touching it.
    let conc = by_name("extreme_concentration");
    let ours = concentration(&exposure_map(&conc.spot, &conc.defi));
    let hhi = ours.hhi.expect("a funded book has an HHI");
    assert!(
        (0.9..1.0).contains(&hhi),
        "expected near-maximal, got {hhi}"
    );
    assert_close_opt(ours.hhi, conc.expected.concentration.hhi, "[conc] hhi");
}

/// A portfolio whose percentages land exactly on a decimal tie. Naive half-away-from-zero
/// rounding disagrees with Python here, and the disagreement is invisible until a user asks why
/// the dashboard and the agent quote different numbers.
#[test]
fn rounding_ties_in_a_real_portfolio_match_python() {
    let c = load();
    let p = c
        .portfolios
        .iter()
        .find(|p| p.name == "rounding_tie_now_pct")
        .expect("corpus should carry the rounding-tie portfolio");
    let plan = rebalance_plan(&p.holdings, p.targets.map(Into::into).as_ref());
    assert_eq!(plan.tiers[0].now_pct, 12.2, "12.25% must round to even");
    assert_close(
        plan.tiers[0].now_pct,
        p.expected.plan.tiers[0].now_pct,
        "tie now_pct",
    );
    // 12.25% vs a 10% target is 2.25pt of drift — inside the 2.5pt band, so Reserve is on
    // target even though the rounded drift *displays* as 2.2. The real gaps are elsewhere:
    // Store holds 87.75% against a 40% target, and Cashflow is empty.
    assert_eq!(plan.tiers[0].action, DriftAction::OnTarget);
    assert_eq!(plan.tiers[0].drift_pct, 2.2);
    assert_eq!(plan.tiers[1].action, DriftAction::Trim);
    assert_eq!(plan.tiers[2].action, DriftAction::Add);
}
