//! Differential parity for the strategy layer, against the Python oracle.
//!
//! `strategy_corpus.json` is generated by running the REAL `pow_mcp.analytics.lending_flags`,
//! `.market_timing` and `.strategy` over synthetic books — every borrow-health band, every
//! posture, both harvest floors, the concentration thresholds, custom and fractional targets,
//! and a large randomized tail. Regenerate with `tests/gen_strategy_corpus.py`.
//!
//! Every user-visible **string** is compared exactly, not just the numbers. These summaries and
//! titles are what the model reads and repeats to the user; a port that gets `$5,420` or
//! `1.8% vs 10% target` subtly wrong produces advice that disagrees with the dashboard, and
//! nobody notices until someone acts on it.
//!
//! The load-bearing test here is
//! `a_position_whose_health_cannot_be_computed_is_never_reported_as_safe`: telling someone their
//! borrow is fine when the health factor could not be computed is the worst thing this system
//! can do.

use serde::Deserialize;

use lyra_analytics::envelope::{Confidence, Flag, Metric, lending_health, liquidation_buffer};
use lyra_analytics::exposure::Concentration;
use lyra_analytics::strategy::{
    self, CandidateAction, FearGreed, LendingRow, MarketTiming, Posture, StrategySignal,
    lending_flags, market_timing, strategy, unassessable_debt_flag,
};
use lyra_analytics::tiers::RebalancePlan;

const REL_TOL: f64 = 1e-9;
const ABS_FLOOR: f64 = 1e-12;

fn approx(a: f64, b: f64) -> bool {
    if a == b {
        return true;
    }
    if !a.is_finite() || !b.is_finite() {
        return false;
    }
    let diff = (a - b).abs();
    diff <= ABS_FLOOR || diff <= REL_TOL * a.abs().max(b.abs())
}

fn assert_close(ours: f64, python: f64, what: &str) {
    assert!(
        approx(ours, python),
        "{what}: rust={ours:?} python={python:?}"
    );
}

fn assert_close_opt(ours: Option<f64>, python: Option<f64>, what: &str) {
    match (ours, python) {
        (None, None) => {}
        (Some(o), Some(p)) => assert_close(o, p, what),
        _ => panic!("{what}: rust={ours:?} python={python:?} — nullability disagrees"),
    }
}

/// Compare a metric field by field — the envelope is the point, so `data_gaps` and `note` are
/// compared exactly, not merely checked for presence.
fn assert_metric(ours: &Metric, python: &Metric, what: &str) {
    assert_close_opt(ours.value, python.value, &format!("{what} value"));
    assert_eq!(ours.unit, python.unit, "{what} unit");
    assert_eq!(ours.confidence, python.confidence, "{what} confidence");
    assert_eq!(ours.data_gaps, python.data_gaps, "{what} data_gaps");
    assert_eq!(ours.note, python.note, "{what} note");
}

// ---------- corpus shapes ----------

#[derive(Debug, Deserialize)]
struct Corpus {
    thresholds: Thresholds,
    lending_flags: Vec<LendingFlagCase>,
    market_timing: Vec<TimingCase>,
    strategies: Vec<StrategyCase>,
}

#[derive(Debug, Deserialize)]
struct Thresholds {
    harvest_floor_usd: f64,
    harvest_floor_pct: f64,
    material_pct: f64,
    conc_watch: f64,
    conc_warn: f64,
    hf_safe: f64,
    hf_target: f64,
}

#[derive(Debug, Deserialize)]
struct LendingFlagCase {
    hf: Option<f64>,
    flags: Vec<Flag>,
    health_factor: Metric,
    liquidation_buffer: Option<f64>,
}

/// The sentiment payload as the engine shapes it. A missing key, an explicit null and an empty
/// object all have to mean the same thing: no reading.
#[derive(Debug, Default, Deserialize)]
struct Sentiment {
    #[serde(default)]
    fear_greed: Option<FearGreed>,
}

#[derive(Debug, Deserialize)]
struct TimingCase {
    name: String,
    #[serde(default)]
    sentiment: Option<Sentiment>,
    timing: MarketTiming,
}

#[derive(Debug, Deserialize)]
struct StrategyCase {
    name: String,
    plan: RebalancePlan,
    concentration: Concentration,
    claim_usd: f64,
    lending: Vec<LendingRow>,
    #[serde(default)]
    sentiment: Option<Sentiment>,
    timing: MarketTiming,
    net_worth: f64,
    expected: Expected,
}

#[derive(Debug, Deserialize)]
struct Expected {
    signals: Vec<StrategySignal>,
    actions: Vec<CandidateAction>,
}

fn load() -> Corpus {
    serde_json::from_str(include_str!("strategy_corpus.json"))
        .expect("strategy_corpus.json should parse")
}

fn fear_greed(sentiment: &Option<Sentiment>) -> Option<&FearGreed> {
    sentiment.as_ref().and_then(|s| s.fear_greed.as_ref())
}

// ---------- thresholds ----------

#[test]
fn the_strategy_thresholds_match_python() {
    let t = load().thresholds;
    assert_close(
        strategy::HARVEST_FLOOR_USD,
        t.harvest_floor_usd,
        "harvest floor $",
    );
    assert_close(
        strategy::HARVEST_FLOOR_PCT,
        t.harvest_floor_pct,
        "harvest floor %",
    );
    assert_close(strategy::MATERIAL_PCT, t.material_pct, "material %");
    assert_close(strategy::CONC_WATCH, t.conc_watch, "concentration watch");
    assert_close(strategy::CONC_WARN, t.conc_warn, "concentration warn");
    assert_close(strategy::HF_SAFE, t.hf_safe, "HF safe floor");
    assert_close(strategy::HF_TARGET, t.hf_target, "HF deleverage target");
}

// ---------- lending flags ----------

#[test]
fn lending_flags_agree_with_python_on_every_health_factor() {
    let corpus = load();
    assert!(corpus.lending_flags.len() > 20, "corpus looks truncated");
    for case in &corpus.lending_flags {
        let ours = lending_flags(case.hf);
        let at = format!("hf={:?}", case.hf);
        assert_eq!(ours.len(), case.flags.len(), "[{at}] flag count: {ours:?}");
        for (ours, python) in ours.iter().zip(&case.flags) {
            assert_eq!(ours.code, python.code, "[{at}] code");
            assert_eq!(ours.severity, python.severity, "[{at}] severity");
            // The message is what the user reads — compared character for character.
            assert_eq!(ours.message, python.message, "[{at}] message");
        }
        assert_metric(&lending_health(case.hf), &case.health_factor, &at);
        assert_close_opt(
            liquidation_buffer(case.hf),
            case.liquidation_buffer,
            &format!("[{at}] liquidation_buffer"),
        );
    }
}

/// The sharpest honesty case in the codebase.
///
/// With no health factor there are no flags — faithful to Python, and correct when the reason is
/// "no debt". What must never happen is that this silence gets *read* as safety: the paired
/// metric is null-with-reason, and when there is debt behind the missing health factor, the
/// unassessable-debt flag says so out loud.
#[test]
fn a_position_whose_health_cannot_be_computed_is_never_reported_as_safe() {
    let corpus = load();
    let missing: Vec<&LendingFlagCase> = corpus
        .lending_flags
        .iter()
        .filter(|c| c.hf.is_none())
        .collect();
    assert!(!missing.is_empty(), "the corpus must exercise a missing HF");

    for case in missing {
        // 1. Python emits no flags, and so do we — agreement, not invention.
        assert!(lending_flags(case.hf).is_empty());
        assert!(case.flags.is_empty());

        // 2. The metric that accompanies those flags is null WITH a reason, never a number.
        let health = lending_health(case.hf);
        assert!(
            health.is_unavailable(),
            "a missing HF must not become a number"
        );
        assert_ne!(health.value, Some(0.0), "0.0 would read as 'liquidated'");
        assert_ne!(health.value, Some(1.0), "1.0 would read as 'at the line'");
        assert_eq!(health.confidence, Confidence::Na);
        assert_eq!(health.data_gaps, case.health_factor.data_gaps);
        assert!(!health.data_gaps.is_empty());

        // 3. There is no buffer to report either — not a zero, not a negative.
        assert_eq!(liquidation_buffer(case.hf), None);

        // 4. And with real debt behind the gap, silence is not acceptable: we flag it.
        //    (This is an addition beyond the Python surface — see the module docs.)
        let flag = unassessable_debt_flag(case.hf, 25_000.0)
            .expect("debt with an uncomputable health factor must be surfaced");
        assert_eq!(flag.code, "health_factor_unavailable");
        assert_eq!(flag.severity, "warn");
        assert!(flag.message.contains("cannot be assessed"));
        // ...while a position with no debt at all stays quiet, as Python does.
        assert_eq!(unassessable_debt_flag(case.hf, 0.0), None);
    }
}

// ---------- market timing ----------

#[test]
fn market_timing_agrees_with_python_on_every_reading() {
    let corpus = load();
    assert!(corpus.market_timing.len() > 20, "corpus looks truncated");
    for case in &corpus.market_timing {
        let ours = market_timing(fear_greed(&case.sentiment));
        let at = &case.name;
        assert_eq!(ours.posture, case.timing.posture, "[{at}] posture");
        assert_eq!(ours.index, case.timing.index, "[{at}] index");
        assert_eq!(
            ours.classification, case.timing.classification,
            "[{at}] classification"
        );
        assert_eq!(ours.confidence, case.timing.confidence, "[{at}] confidence");
        assert_eq!(ours.basis, case.timing.basis, "[{at}] basis");
        assert_eq!(ours.gaps, case.timing.gaps, "[{at}] gaps");
    }
}

/// No sentiment feed means no tilt — reported as unknown, never as a neutral 50.
#[test]
fn a_missing_sentiment_feed_is_null_with_reason_not_a_neutral_reading() {
    let corpus = load();
    let mut checked = 0;
    for case in corpus
        .market_timing
        .iter()
        .filter(|c| c.timing.index.is_none())
    {
        let ours = market_timing(fear_greed(&case.sentiment));
        let at = &case.name;
        assert_eq!(ours.index, None, "[{at}]");
        assert_eq!(ours.posture, Posture::Neutral, "[{at}] no feed = no tilt");
        assert_eq!(ours.confidence, Confidence::Na, "[{at}]");

        let metric = ours.metric(None);
        assert!(metric.is_unavailable(), "[{at}] the tilt must be null");
        assert_ne!(
            metric.value,
            Some(50.0),
            "[{at}] 50 is a reading, not an absence"
        );
        assert_ne!(metric.value, Some(0.0), "[{at}]");
        assert_eq!(
            metric.data_gaps, case.timing.gaps,
            "[{at}] reason must match"
        );
        assert!(!metric.data_gaps.is_empty(), "[{at}] null needs a reason");
        checked += 1;
    }
    assert!(
        checked >= 5,
        "expected several no-feed cases, saw {checked}"
    );
}

// ---------- strategy ----------

fn assert_signals(ours: &[StrategySignal], python: &[StrategySignal], at: &str) {
    assert_eq!(
        ours.iter().map(|s| s.kind.as_str()).collect::<Vec<_>>(),
        python.iter().map(|s| s.kind.as_str()).collect::<Vec<_>>(),
        "[{at}] signal kinds (and their order)"
    );
    for (i, (ours, python)) in ours.iter().zip(python).enumerate() {
        let at = format!("[{at}] signal {i} ({})", python.kind);
        assert_eq!(ours.severity, python.severity, "{at} severity");
        assert_eq!(ours.summary, python.summary, "{at} summary");
        assert_metric(&ours.metric, &python.metric, &format!("{at} metric"));
    }
}

fn assert_actions(ours: &[CandidateAction], python: &[CandidateAction], at: &str) {
    assert_eq!(
        ours.iter().map(|a| a.action.as_str()).collect::<Vec<_>>(),
        python.iter().map(|a| a.action.as_str()).collect::<Vec<_>>(),
        "[{at}] actions (and their ranking)"
    );
    for (i, (ours, python)) in ours.iter().zip(python).enumerate() {
        let at = format!("[{at}] action {i} ({})", python.action);
        assert_eq!(ours.priority, python.priority, "{at} priority");
        assert_eq!(ours.title, python.title, "{at} title");
        assert_eq!(ours.rationale, python.rationale, "{at} rationale");
        assert_close_opt(ours.size_usd, python.size_usd, &format!("{at} size_usd"));
        assert_eq!(ours.confidence, python.confidence, "{at} confidence");
        assert_eq!(ours.assumptions, python.assumptions, "{at} assumptions");
        assert_eq!(
            ours.reversibility, python.reversibility,
            "{at} reversibility"
        );
    }
}

#[test]
fn strategy_agrees_with_python_on_every_book() {
    let corpus = load();
    assert!(corpus.strategies.len() > 100, "corpus looks truncated");
    let mut compared = 0;
    for case in &corpus.strategies {
        // Recompute the timing from the raw sentiment rather than trusting the corpus copy, so
        // the whole chain sentiment -> timing -> strategy is under test.
        let timing = market_timing(fear_greed(&case.sentiment));
        assert_eq!(
            timing.posture, case.timing.posture,
            "[{}] posture",
            case.name
        );
        assert_eq!(timing.basis, case.timing.basis, "[{}] basis", case.name);

        let outcome = strategy(
            &case.plan,
            &case.concentration,
            case.claim_usd,
            &case.lending,
            &timing,
            case.net_worth,
        );
        assert_signals(&outcome.signals, &case.expected.signals, &case.name);
        assert_actions(&outcome.actions, &case.expected.actions, &case.name);
        compared += outcome.signals.len() + outcome.actions.len();
    }
    assert!(
        compared > 1500,
        "expected a broad corpus, only compared {compared} signals+actions"
    );
}

/// Ranking is the substance of the strategy: protecting the book must always outrank growth, and
/// the priorities that come back must be a clean 1..n.
#[test]
fn protection_always_outranks_growth_and_priorities_are_renumbered() {
    for case in load().strategies {
        let outcome = strategy(
            &case.plan,
            &case.concentration,
            case.claim_usd,
            &case.lending,
            &market_timing(fear_greed(&case.sentiment)),
            case.net_worth,
        );
        let priorities: Vec<usize> = outcome.actions.iter().map(|a| a.priority).collect();
        assert_eq!(
            priorities,
            (1..=outcome.actions.len()).collect::<Vec<_>>(),
            "[{}] priorities must be a clean sequence",
            case.name
        );
        if let Some(pos) = outcome
            .actions
            .iter()
            .position(|a| a.action == "deleverage")
        {
            assert_eq!(pos, 0, "[{}] deleveraging is always first", case.name);
        }
        // Signals are ordered warn -> watch -> info, so the loudest is never buried.
        let severities: Vec<_> = outcome.signals.iter().map(|s| s.severity).collect();
        let mut sorted = severities.clone();
        sorted.sort();
        assert_eq!(severities, sorted, "[{}] signal ordering", case.name);
    }
}

/// A book with no exposure to measure produces no concentration signal at all — rather than a
/// reassuring "0% concentration", which would be a claim the data cannot support.
#[test]
fn unmeasurable_concentration_produces_no_signal_rather_than_a_comforting_zero() {
    let corpus = load();
    let case = corpus
        .strategies
        .iter()
        .find(|c| c.name == "concentration_unmeasurable")
        .expect("corpus should carry the unmeasurable-concentration case");
    assert!(case.concentration.hhi.is_none());

    let outcome = strategy(
        &case.plan,
        &case.concentration,
        case.claim_usd,
        &case.lending,
        &market_timing(fear_greed(&case.sentiment)),
        case.net_worth,
    );
    assert!(
        !outcome.signals.iter().any(|s| s.kind == "concentration"),
        "an unmeasurable concentration must stay silent, not claim diversification"
    );
    assert!(
        !outcome
            .actions
            .iter()
            .any(|a| a.action == "reduce_concentration")
    );
    assert_signals(&outcome.signals, &case.expected.signals, &case.name);
}
