//! Differential parity for the concentrated-liquidity maths, against the Python oracle.
//!
//! `lp_corpus.json` is generated by `lp_corpus_gen.py` running the real `portfolio.py` functions
//! over 2,836 cases: every tick across the full `±887272` domain, liquidity spanning the whole
//! uint128 range (both sides of the 2^53 exact-integer boundary), sqrt prices placed *exactly* on
//! the branch seams, decimal pairs in both orientations, and the overflow/underflow tails where
//! Python raises `OverflowError` and we saturate to infinity.
//!
//! Floats are compared to 1e-9 **relative**; integers, booleans, `None`-ness and symbol
//! orientation must match **exactly**. The tolerance is a ceiling, not a target — the assertions
//! report the maximum observed drift so a regression that stays inside the ceiling is still
//! visible.
//!
//! This is money code: an LP valuation that is quietly wrong looks exactly like one that is
//! right, so the corpus is the gate, not the unit tests.

use serde::Deserialize;

use lyra_chain::lp_math::{
    amounts_from_liquidity, blend_change, fee_tick_spacing, lp_range, s24, sqrt_ratio_at_tick,
    u256_hex_to_f64,
};

/// Relative tolerance for every float the port computes.
const TOL: f64 = 1e-9;

/// Tighter bar for `u256_hex_to_f64`: it is a pure `int -> f64` conversion, so anything beyond a
/// few ULP would mean the widening is wrong rather than that the maths drifted.
const PARSE_TOL: f64 = 1e-15;

#[derive(Debug, Deserialize)]
struct Corpus {
    sqrt_ratio: Vec<SqrtCase>,
    amounts: Vec<AmountCase>,
    lp_range: Vec<RangeCase>,
    blend: Vec<BlendCase>,
    s24: Vec<S24Case>,
    fee_spacing: Vec<FeeCase>,
    u256: Vec<U256Case>,
}

#[derive(Debug, Deserialize)]
struct SqrtCase {
    tick: i32,
    sqrt: f64,
}

#[derive(Debug, Deserialize)]
struct AmountCase {
    tick_lower: i32,
    tick_upper: i32,
    /// Decimal string: liquidity is a uint128 and does not survive a JSON number.
    liquidity: String,
    /// Hex string: `sqrtPriceX96` is a uint160 and does not fit in `u128` at all.
    sqrt_p_hex: String,
    amt0: f64,
    amt1: f64,
}

#[derive(Debug, Deserialize)]
struct RangeCase {
    tick_lower: i32,
    tick_upper: i32,
    cur_tick: i32,
    d0: i32,
    d1: i32,
    s0: String,
    s1: String,
    /// `Some` if the Python raised; the Rust must then be a documented deliberate decision.
    error: Option<String>,
    lower: Option<f64>,
    upper: Option<f64>,
    cur: Option<f64>,
    base: Option<String>,
    quote: Option<String>,
    full: Option<bool>,
}

#[derive(Debug, Deserialize)]
struct BlendCase {
    v0: f64,
    c0: Option<f64>,
    v1: f64,
    c1: Option<f64>,
    out: Option<f64>,
}

#[derive(Debug, Deserialize)]
struct S24Case {
    x: u32,
    out: i32,
}

#[derive(Debug, Deserialize)]
struct FeeCase {
    fee: u32,
    spacing: Option<i32>,
}

#[derive(Debug, Deserialize)]
struct U256Case {
    hex: String,
    f: f64,
}

fn load() -> Corpus {
    let raw = include_str!("lp_corpus.json");
    serde_json::from_str(raw).expect("lp_corpus.json should parse")
}

/// Relative difference, defined so that a sign flip or a zero-vs-nonzero disagreement scores 1.0
/// (i.e. always fails) rather than dividing by zero.
fn drift(py: f64, rs: f64) -> f64 {
    if py == rs {
        return 0.0;
    }
    let scale = py.abs().max(rs.abs());
    if scale == 0.0 {
        0.0
    } else {
        (py - rs).abs() / scale
    }
}

/// Accumulates the worst relative drift seen, so every test can report a number rather than just
/// "it passed".
#[derive(Default)]
struct Drift {
    max: f64,
    at: String,
}

impl Drift {
    fn record(&mut self, py: f64, rs: f64, what: impl FnOnce() -> String) {
        let d = drift(py, rs);
        if d > self.max {
            self.max = d;
            self.at = what();
        }
    }

    fn assert_within(&self, tol: f64, label: &str, cases: usize) {
        assert!(
            self.max <= tol,
            "{label}: max relative drift {:.3e} exceeds {tol:.0e} over {cases} cases, worst at {}",
            self.max,
            self.at
        );
        eprintln!(
            "{label}: {cases} cases, max relative drift {:.3e} (worst: {})",
            self.max,
            if self.at.is_empty() {
                "exact"
            } else {
                &self.at
            }
        );
    }
}

#[test]
fn the_corpus_is_big_enough_to_mean_something() {
    let c = load();
    let total = c.sqrt_ratio.len()
        + c.amounts.len()
        + c.lp_range.len()
        + c.blend.len()
        + c.s24.len()
        + c.fee_spacing.len()
        + c.u256.len();
    assert!(total >= 500, "corpus looks truncated: {total} cases");
    eprintln!("lp_corpus.json: {total} cases");
}

#[test]
fn sqrt_ratio_at_tick_agrees_with_python_across_the_whole_tick_domain() {
    let cases = load().sqrt_ratio;
    let mut d = Drift::default();
    for c in &cases {
        let ours = sqrt_ratio_at_tick(c.tick);
        assert!(ours.is_finite(), "tick {} produced {ours}", c.tick);
        d.record(c.sqrt, ours, || format!("tick {}", c.tick));
    }
    // The corpus must actually reach the bounds, or "full domain" is a lie.
    assert!(cases.iter().any(|c| c.tick == 887_272));
    assert!(cases.iter().any(|c| c.tick == -887_272));
    d.assert_within(TOL, "sqrt_ratio_at_tick", cases.len());
}

#[test]
fn amounts_from_liquidity_agrees_with_python_including_on_the_branch_seams() {
    let cases = load().amounts;
    let mut d = Drift::default();
    for c in &cases {
        let liq: u128 = c.liquidity.parse().expect("liquidity should be a u128");
        let sqrt_p = u256_hex_to_f64(&c.sqrt_p_hex).expect("sqrtP should parse");
        let sqrt_a = sqrt_ratio_at_tick(c.tick_lower);
        let sqrt_b = sqrt_ratio_at_tick(c.tick_upper);
        let (amt0, amt1) = amounts_from_liquidity(liq, sqrt_p, sqrt_a, sqrt_b);

        assert!(
            amt0.is_finite() && amt1.is_finite(),
            "non-finite amounts for {c:?}: {amt0} {amt1}"
        );
        let label = || {
            format!(
                "ticks [{}, {}] liq={} sqrtP={}",
                c.tick_lower, c.tick_upper, c.liquidity, c.sqrt_p_hex
            )
        };
        d.record(c.amt0, amt0, || format!("amt0 @ {}", label()));
        d.record(c.amt1, amt1, || format!("amt1 @ {}", label()));
    }
    d.assert_within(TOL, "amounts_from_liquidity", cases.len());
}

#[test]
fn amounts_from_liquidity_never_loses_a_uint160_sqrt_price_to_u128() {
    // The specific failure this whole module is shaped around: a sqrtPriceX96 above u128::MAX.
    // If any corpus case has one and we still agree with Python, the widening is doing its job.
    let cases = load().amounts;
    let wide = cases
        .iter()
        .filter(|c| u256_hex_to_f64(&c.sqrt_p_hex).is_some_and(|v| v > u128::MAX as f64))
        .count();
    assert!(
        wide > 0,
        "corpus has no sqrtP beyond u128::MAX, so it cannot prove the widening matters"
    );
    eprintln!("{wide} of {} cases carry a sqrtP > u128::MAX", cases.len());
}

#[test]
fn lp_range_agrees_with_python_on_bands_symbols_and_the_full_range_flag() {
    let cases = load().lp_range;
    let mut d = Drift::default();
    for c in &cases {
        assert!(
            c.error.is_none(),
            "the corpus contains a Python failure that the port must decide about: {c:?}"
        );
        let band = lp_range(
            c.tick_lower,
            c.tick_upper,
            c.cur_tick,
            c.d0,
            c.d1,
            &c.s0,
            &c.s1,
        );
        let label = format!(
            "band [{}, {}] cur={} decimals {}/{}",
            c.tick_lower, c.tick_upper, c.cur_tick, c.d0, c.d1
        );

        // Orientation and the full-range flag are decisions, not measurements: exact or bust.
        assert_eq!(Some(band.base.to_string()), c.base, "base @ {label}");
        assert_eq!(Some(band.quote.to_string()), c.quote, "quote @ {label}");
        assert_eq!(Some(band.full), c.full, "full @ {label}");

        for (name, py, rs) in [
            ("lower", c.lower, band.lower),
            ("upper", c.upper, band.upper),
            ("cur", c.cur, band.cur),
        ] {
            assert_eq!(
                py.is_none(),
                rs.is_none(),
                "{name} finiteness @ {label}: python={py:?} rust={rs:?}"
            );
            if let (Some(py), Some(rs)) = (py, rs) {
                d.record(py, rs, || format!("{name} @ {label}"));
            }
        }
    }
    d.assert_within(TOL, "lp_range", cases.len());
}

#[test]
fn the_lp_range_corpus_exercises_both_orientations_and_both_tails() {
    // A corpus where nothing inverted and nothing overflowed would pass while testing very little.
    let cases = load().lp_range;
    let inverted = cases
        .iter()
        .filter(|c| c.base.as_deref() == Some("BBB"))
        .count();
    let full = cases.iter().filter(|c| c.full == Some(true)).count();
    let clipped = cases.iter().filter(|c| c.upper.is_none()).count();
    assert!(inverted > 50, "only {inverted} inverted bands");
    assert!(full > 50, "only {full} full-range bands");
    assert!(clipped > 0, "no overflowed upper edge in the corpus");
    eprintln!("lp_range: {inverted} inverted, {full} full-range, {clipped} overflowed edges");
}

#[test]
fn blend_change_agrees_with_python_including_the_falsy_zero_paths() {
    let cases = load().blend;
    let mut d = Drift::default();
    for c in &cases {
        let ours = blend_change(c.v0, c.c0, c.v1, c.c1);
        let label = format!("v0={} c0={:?} v1={} c1={:?}", c.v0, c.c0, c.v1, c.c1);
        assert_eq!(
            c.out.is_none(),
            ours.is_none(),
            "None-ness @ {label}: python={:?} rust={ours:?}",
            c.out
        );
        if let (Some(py), Some(rs)) = (c.out, ours) {
            d.record(py, rs, || label.clone());
        }
    }
    // Both verdicts must appear, or the None path is untested.
    assert!(cases.iter().any(|c| c.out.is_none()));
    assert!(cases.iter().any(|c| c.out.is_some()));
    d.assert_within(TOL, "blend_change", cases.len());
}

#[test]
fn s24_agrees_with_python_exactly_across_the_whole_24_bit_domain() {
    let cases = load().s24;
    for c in &cases {
        assert_eq!(s24(c.x), c.out, "s24({})", c.x);
    }
    assert!(cases.iter().any(|c| c.out < 0), "no negative ticks decoded");
    assert!(cases.iter().any(|c| c.out > 0), "no positive ticks decoded");
    eprintln!("s24: {} cases, all exact", cases.len());
}

#[test]
fn fee_tick_spacing_agrees_with_python_exactly() {
    let cases = load().fee_spacing;
    for c in &cases {
        assert_eq!(fee_tick_spacing(c.fee), c.spacing, "fee {}", c.fee);
    }
    assert!(
        cases.iter().any(|c| c.spacing.is_none()),
        "no misses tested"
    );
    eprintln!("fee_tick_spacing: {} cases, all exact", cases.len());
}

#[test]
fn u256_hex_to_f64_matches_pythons_own_int_to_float_conversion() {
    let cases = load().u256;
    let mut d = Drift::default();
    for c in &cases {
        let ours = u256_hex_to_f64(&c.hex).unwrap_or_else(|| panic!("{} should parse", c.hex));
        d.record(c.f, ours, || c.hex.clone());
    }
    assert!(
        cases.iter().any(|c| c.f > u128::MAX as f64),
        "no case beyond u128::MAX"
    );
    d.assert_within(PARSE_TOL, "u256_hex_to_f64", cases.len());
}
