//! Differential parity for the market-context maths, against the Python oracle.
//!
//! `market_corpus.json` is generated by `market_corpus_gen.py` (in this directory) from
//! `portfolio.btc_rainbow` and `portfolio._zoned`. Both are pure, so they can be compared
//! exhaustively offline — no chain access, no network, no flakiness.
//!
//! The corpus is built to land on the places a hand-rewrite drifts:
//!
//! * **Every band and zone edge, plus one ULP either side.** The two functions use *opposite*
//!   conventions — the rainbow's `ratio >= min_ratio` is inclusive from below, `_zoned`'s
//!   `value < upper` is exclusive from below — and a rewrite that made them consistent would be
//!   wrong in a way no midpoint test can see.
//! * **Eleven different day counts**, since the rainbow's fair value moves with Bitcoin's age. The
//!   Python reads `date.today()`, so the generator shifts `BTC_GENESIS` instead of freezing time.
//! * **Rounding halves.** Python rounds half-to-even on the exact decimal value of the double, so
//!   `round(0.0625, 3)` is `0.062`; the obvious `(x * 1000.0).round() / 1000.0` gives `0.063`.
//!
//! Labels and colours are compared as **exact strings** — a mismatch there paints the wrong colour
//! on the Sentiment page even when the number underneath is right.
//!
//! Every float in the corpus is a **decimal string**, not a JSON number, and is loaded with
//! `str::parse::<f64>`. `serde_json`'s number parser takes a fast path that is off by up to one ULP
//! unless the `float_roundtrip` feature is enabled, and a corpus made of band edges and their
//! immediate neighbours is precisely the input that trips it — a value one ULP below an edge loads
//! as the edge itself and then reports a divergence the port does not have. Strings sidestep it
//! without a dependency change; if `float_roundtrip` is ever turned on crate-wide this can go back
//! to plain JSON numbers.

use serde::{Deserialize, Deserializer};

use lyra_chain::market::{
    MVRV_ZONES, PUELL_ZONES, RAINBOW_BANDS, SOPR_ZONES, Zone, btc_rainbow_at, zoned,
};

/// Numbers must agree to this relative tolerance. In practice they agree bit for bit — both sides
/// do the same IEEE-754 operations in the same order — but a rounding helper that drifted in the
/// last place should fail loudly rather than silently.
const TOLERANCE: f64 = 1e-9;

/// A float carried through JSON as its shortest round-trip decimal string, so it reloads bit-exact.
fn exact<'de, D: Deserializer<'de>>(deserializer: D) -> Result<f64, D::Error> {
    let raw = String::deserialize(deserializer)?;
    raw.parse()
        .map_err(|_| serde::de::Error::custom(format!("not a float: {raw:?}")))
}

/// The same, for a field the oracle may report as absent.
fn exact_opt<'de, D: Deserializer<'de>>(deserializer: D) -> Result<Option<f64>, D::Error> {
    Option::<String>::deserialize(deserializer)?
        .map(|raw| {
            raw.parse()
                .map_err(|_| serde::de::Error::custom(format!("not a float: {raw:?}")))
        })
        .transpose()
}

#[derive(Debug, Deserialize)]
struct Corpus {
    rainbow_bands: Vec<BandSpec>,
    zone_sets: ZoneSets,
    rainbow: Vec<RainbowCase>,
    zoned: Vec<ZonedCase>,
}

#[derive(Debug, Deserialize)]
struct BandSpec {
    #[serde(deserialize_with = "exact")]
    min_ratio: f64,
    label: String,
    color: String,
}

#[derive(Debug, Deserialize)]
struct ZoneSpec {
    #[serde(deserialize_with = "exact")]
    upper: f64,
    label: String,
    color: String,
}

#[derive(Debug, Deserialize)]
struct ZoneSets {
    mvrv_zscore: Vec<ZoneSpec>,
    sopr: Vec<ZoneSpec>,
    puell: Vec<ZoneSpec>,
}

#[derive(Debug, Deserialize)]
struct RainbowCase {
    days: u32,
    #[serde(deserialize_with = "exact")]
    price: f64,
    band: Option<PyRainbow>,
}

#[derive(Debug, Deserialize)]
struct PyRainbow {
    label: String,
    color: String,
    #[serde(deserialize_with = "exact")]
    ratio: f64,
    fair_usd: i64,
}

#[derive(Debug, Deserialize)]
struct ZonedCase {
    metric: String,
    dp: usize,
    #[serde(deserialize_with = "exact_opt")]
    value: Option<f64>,
    /// True where the Python raised `StopIteration` — a value at or above the top zone bound.
    raises: bool,
    zone: Option<PyZoned>,
}

#[derive(Debug, Deserialize)]
struct PyZoned {
    #[serde(deserialize_with = "exact")]
    value: f64,
    label: String,
    color: String,
}

fn load() -> Corpus {
    serde_json::from_str(include_str!("market_corpus.json"))
        .expect("market_corpus.json should parse")
}

fn zones_for(metric: &str) -> (&'static [Zone], usize) {
    match metric {
        "mvrv_zscore" => (&MVRV_ZONES, 2),
        "sopr" => (&SOPR_ZONES, 3),
        "puell" => (&PUELL_ZONES, 2),
        other => panic!("corpus names a metric the port does not have: {other}"),
    }
}

/// Equal within [`TOLERANCE`] relative, with exact zero handled directly since a relative tolerance
/// is meaningless there.
fn close(a: f64, b: f64) -> bool {
    if a == b {
        return true;
    }
    if !a.is_finite() || !b.is_finite() {
        return false;
    }
    (a - b).abs() <= TOLERANCE * a.abs().max(b.abs()).max(1.0)
}

#[test]
fn the_band_table_matches_pythons_thresholds_labels_and_colours() {
    let corpus = load();
    assert_eq!(
        corpus.rainbow_bands.len(),
        RAINBOW_BANDS.len(),
        "the number of bands changed"
    );
    for (py, rs) in corpus.rainbow_bands.iter().zip(RAINBOW_BANDS.iter()) {
        assert_eq!(py.min_ratio, rs.min_ratio, "threshold for {:?}", py.label);
        assert_eq!(py.label, rs.label);
        assert_eq!(py.color, rs.color, "colour for {:?}", py.label);
    }
}

#[test]
fn every_zone_table_matches_pythons_bounds_labels_and_colours() {
    let corpus = load();
    for (metric, py_zones) in [
        ("mvrv_zscore", &corpus.zone_sets.mvrv_zscore),
        ("sopr", &corpus.zone_sets.sopr),
        ("puell", &corpus.zone_sets.puell),
    ] {
        let (rs_zones, _) = zones_for(metric);
        assert_eq!(py_zones.len(), rs_zones.len(), "zone count for {metric}");
        for (py, rs) in py_zones.iter().zip(rs_zones.iter()) {
            assert_eq!(py.upper, rs.upper, "{metric} bound for {:?}", py.label);
            assert_eq!(py.label, rs.label, "{metric} label");
            assert_eq!(py.color, rs.color, "{metric} colour for {:?}", py.label);
        }
    }
}

#[test]
fn the_rainbow_agrees_with_python_on_every_price_and_day_count() {
    let corpus = load();
    assert!(
        corpus.rainbow.len() > 500,
        "corpus looks truncated: {}",
        corpus.rainbow.len()
    );

    let mut disagreements = Vec::new();
    for case in &corpus.rainbow {
        let ours = btc_rainbow_at(Some(case.price), case.days);
        let complaint = match (&case.band, &ours) {
            (None, None) => None,
            (Some(py), None) => Some(format!("python={:?} rust=None", py.label)),
            (None, Some(rs)) => Some(format!("python=None rust={:?}", rs.label)),
            (Some(py), Some(rs)) => {
                if py.label != rs.label {
                    Some(format!("label python={:?} rust={:?}", py.label, rs.label))
                } else if py.color != rs.color {
                    Some(format!("color python={:?} rust={:?}", py.color, rs.color))
                } else if !close(py.ratio, rs.ratio) {
                    Some(format!("ratio python={} rust={}", py.ratio, rs.ratio))
                } else if py.fair_usd != rs.fair_usd {
                    Some(format!(
                        "fair_usd python={} rust={}",
                        py.fair_usd, rs.fair_usd
                    ))
                } else {
                    None
                }
            }
        };
        if let Some(complaint) = complaint {
            disagreements.push(format!(
                "days={} price={:e} — {complaint}",
                case.days, case.price
            ));
        }
    }

    assert!(
        disagreements.is_empty(),
        "{} of {} rainbow cases disagree:\n{}",
        disagreements.len(),
        corpus.rainbow.len(),
        disagreements
            .iter()
            .take(20)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

#[test]
fn the_zone_classifier_agrees_with_python_on_every_metric_reading() {
    let corpus = load();
    let mut disagreements = Vec::new();

    for case in &corpus.zoned {
        let (zones, dp) = zones_for(&case.metric);
        assert_eq!(case.dp, dp, "{} decimal places", case.metric);
        let ours = zoned(case.value, zones, dp);

        // Where the Python raised, the port must report a missing metric rather than a value —
        // it is the only sane way to render an exception as a UI tile.
        let expected_none = case.raises || case.zone.is_none();
        let complaint = match (&case.zone, &ours) {
            (None, None) if expected_none => None,
            (None, Some(rs)) => Some(format!(
                "python={} rust={:?}",
                if case.raises { "StopIteration" } else { "None" },
                rs.label
            )),
            (Some(py), None) => Some(format!("python={:?} rust=None", py.label)),
            (Some(py), Some(rs)) => {
                if py.label != rs.label {
                    Some(format!("label python={:?} rust={:?}", py.label, rs.label))
                } else if py.color != rs.color {
                    Some(format!("color python={:?} rust={:?}", py.color, rs.color))
                } else if !close(py.value, rs.value) {
                    Some(format!("value python={} rust={}", py.value, rs.value))
                } else {
                    None
                }
            }
            (None, None) => None,
        };
        if let Some(complaint) = complaint {
            disagreements.push(format!(
                "{} value={:?} — {complaint}",
                case.metric, case.value
            ));
        }
    }

    assert!(
        disagreements.is_empty(),
        "{} of {} zone cases disagree:\n{}",
        disagreements.len(),
        corpus.zoned.len(),
        disagreements
            .iter()
            .take(20)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

#[test]
fn the_corpus_actually_exercises_both_boundary_conventions() {
    // A corpus that never sat exactly on an edge, or only ever produced one band, would pass the
    // comparisons above while testing nothing that matters.
    let corpus = load();

    let bands: std::collections::HashSet<_> = corpus
        .rainbow
        .iter()
        .filter_map(|c| c.band.as_ref().map(|b| b.label.clone()))
        .collect();
    assert_eq!(
        bands.len(),
        RAINBOW_BANDS.len(),
        "every band should appear: {bands:?}"
    );
    assert!(
        corpus.rainbow.iter().any(|c| c.band.is_none()),
        "the no-band path (zero/negative price) should be covered"
    );

    // Keyed by (metric, label): "Undervalued" is a zone of both MVRV and Puell, so counting bare
    // labels would undercount and let a whole zone go unexercised.
    let labels: std::collections::HashSet<_> = corpus
        .zoned
        .iter()
        .filter_map(|c| c.zone.as_ref().map(|z| (c.metric.clone(), z.label.clone())))
        .collect();
    let total_zones = MVRV_ZONES.len() + SOPR_ZONES.len() + PUELL_ZONES.len();
    assert_eq!(
        labels.len(),
        total_zones,
        "every zone should appear: {labels:?}"
    );
    assert!(
        corpus.zoned.iter().any(|c| c.raises),
        "the past-the-top-zone case should be covered"
    );
    assert!(
        corpus.zoned.iter().any(|c| c.value.is_none()),
        "the missing-metric case should be covered"
    );
}
