//! Differential parity for the portfolio data model, against the Python oracle.
//!
//! `model_corpus.json` is generated by `model_corpus_gen.py` (in this directory) by calling
//! the real `portfolio._position`, `_lp_position`, `_vfat_stamp_meta`, `_lp_range`,
//! `_chain_result` and `_wallet`. Nothing in the corpus is a hand-written expectation, so a
//! misreading of the oracle cannot be baked into both sides at once.
//!
//! What is asserted, per case:
//!
//! 1. **Key sets, recursively.** A key Python emits that the Rust type drops is a blank panel
//!    in the UI — `types.ts` reads these objects directly. A key Rust adds that Python does not
//!    emit is harmless to the front end but still reported, because it means the model is
//!    guessing. Both directions are collected across the whole tree and reported together with
//!    their JSON paths, rather than failing on the first one.
//! 2. **Values.** Numbers are compared numerically so Python's `42` and Rust's `42.0` agree
//!    (JSON has one number type; `serde_json` keeps the int/float distinction internally but
//!    no consumer of this API can see it). Everything else is compared exactly.
//! 3. **Round-trip.** Python's JSON → Rust type → JSON must be unchanged. This is what makes
//!    the *absent* / *null* distinction load-bearing: a `rewards_usd: null` that deserialises
//!    into a plain `Option<f64>` would come back with the key missing.
//!
//! The three-state problem this model exists to solve: `_position` writes `rewards_usd`
//! **inside** the `if rewards is not None` branch, so
//!
//! * `rewards=[…], rewards_usd=1.0` → both keys, both values
//! * `rewards=[…], rewards_usd=None` → both keys, `rewards_usd: null`
//! * `rewards=None, rewards_usd=1.0` → **neither key**, value discarded
//!
//! No single `Option<f64>` can represent all three, which is why `Nullable<T>` exists. The
//! same applies to the whole `_vfat_stamp_lifecycle` block (`deployed_at`, `updated_at`,
//! `last_action`, `last_harvest_at`, `cycle_start`), to `change24h`, and to spot's
//! `change24h`/`coin`.
//!
//! Floats: the corpus is built from exactly-representable values (halves, quarters, powers of
//! two) wherever a Rust struct is hand-built below, so no tolerance is needed there. The
//! tick-maths cases carry irrational values, but both sides of the comparison get their `f64`
//! from the same `serde_json` parse of the same bytes, so they are bit-identical regardless of
//! whether the `float_roundtrip` feature is on.

use std::collections::BTreeSet;

use serde::Deserialize;
use serde_json::{Value, json};

use lyra_chain::market::{FearGreed, Rainbow, Rates};
use lyra_chain::model::{
    BotInfo, BotWeight, ChainBucket, LendingHealth, PortfolioSentiment, PortfolioSnapshot,
    Position, PriceBand, RangePct, SpotToken, SubBot, TokenAmt, Wallet, fallback_rates,
};

const CORPUS: &str = include_str!("model_corpus.json");

#[derive(Debug, Deserialize)]
struct Corpus {
    cases: Vec<Case>,
}

#[derive(Debug, Deserialize)]
struct Case {
    name: String,
    /// Which Rust type this JSON must load into.
    kind: String,
    /// Why the case exists — echoed into failure output so a break explains itself.
    note: String,
    json: Value,
}

fn corpus() -> Corpus {
    serde_json::from_str(CORPUS).expect("model_corpus.json is malformed")
}

fn case(name: &str) -> Value {
    corpus()
        .cases
        .into_iter()
        .find(|c| c.name == name)
        .unwrap_or_else(|| panic!("no corpus case named {name:?}"))
        .json
}

// -------------------------------------------------------------------------------------------
// Structural diff
// -------------------------------------------------------------------------------------------

/// One way the port's JSON differs from the oracle's.
#[derive(Debug)]
enum Diff {
    /// A key the oracle emits and the port does not. This is the one that breaks the UI.
    MissingKey(String),
    /// A key the port emits and the oracle does not. Harmless to the front end, reported anyway.
    ExtraKey(String),
    ArrayLen(String, usize, usize),
    Value(String, String, String),
    Type(String, &'static str, &'static str),
}

impl std::fmt::Display for Diff {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Diff::MissingKey(p) => write!(f, "MISSING KEY {p} — python emits it, rust drops it"),
            Diff::ExtraKey(p) => write!(f, "EXTRA KEY   {p} — rust emits it, python does not"),
            Diff::ArrayLen(p, py, rs) => write!(f, "ARRAY LEN   {p}: python {py}, rust {rs}"),
            Diff::Value(p, py, rs) => write!(f, "VALUE       {p}: python {py}, rust {rs}"),
            Diff::Type(p, py, rs) => write!(f, "TYPE        {p}: python {py}, rust {rs}"),
        }
    }
}

fn type_name(v: &Value) -> &'static str {
    match v {
        Value::Null => "null",
        Value::Bool(_) => "bool",
        Value::Number(_) => "number",
        Value::String(_) => "string",
        Value::Array(_) => "array",
        Value::Object(_) => "object",
    }
}

/// Walk `python` and `rust` together, collecting every structural and value difference.
///
/// Key sets are compared as sets at every object, so absence is a first-class result rather
/// than something inferred from a null.
fn diff(path: &str, python: &Value, rust: &Value, out: &mut Vec<Diff>) {
    match (python, rust) {
        (Value::Object(py), Value::Object(rs)) => {
            let py_keys: BTreeSet<&String> = py.keys().collect();
            let rs_keys: BTreeSet<&String> = rs.keys().collect();
            for k in py_keys.difference(&rs_keys) {
                out.push(Diff::MissingKey(format!("{path}.{k}")));
            }
            for k in rs_keys.difference(&py_keys) {
                out.push(Diff::ExtraKey(format!("{path}.{k}")));
            }
            for k in py_keys.intersection(&rs_keys) {
                diff(&format!("{path}.{k}"), &py[*k], &rs[*k], out);
            }
        }
        (Value::Array(py), Value::Array(rs)) => {
            if py.len() != rs.len() {
                out.push(Diff::ArrayLen(path.to_string(), py.len(), rs.len()));
                return;
            }
            for (i, (a, b)) in py.iter().zip(rs).enumerate() {
                diff(&format!("{path}[{i}]"), a, b, out);
            }
        }
        // JSON has a single number type; the oracle emits `round(fair)` as an int and
        // `tick_spacing` as an int, so an int/float mismatch is not a shape difference.
        (Value::Number(py), Value::Number(rs)) => {
            let (a, b) = (py.as_f64(), rs.as_f64());
            if a != b {
                out.push(Diff::Value(
                    path.to_string(),
                    py.to_string(),
                    rs.to_string(),
                ));
            }
        }
        _ if type_name(python) != type_name(rust) => {
            out.push(Diff::Type(
                path.to_string(),
                type_name(python),
                type_name(rust),
            ));
        }
        _ if python != rust => {
            out.push(Diff::Value(
                path.to_string(),
                python.to_string(),
                rust.to_string(),
            ));
        }
        _ => {}
    }
}

fn assert_same(label: &str, note: &str, python: &Value, rust: &Value) {
    let mut diffs = Vec::new();
    diff("", python, rust, &mut diffs);
    assert!(
        diffs.is_empty(),
        "\n{label}\n  why this case exists: {note}\n  {}\n  python: {}\n  rust:   {}\n",
        diffs
            .iter()
            .map(Diff::to_string)
            .collect::<Vec<_>>()
            .join("\n  "),
        serde_json::to_string(python).unwrap(),
        serde_json::to_string(rust).unwrap(),
    );
}

/// Load the case's JSON into `T`, serialise it back, and require the result to be identical.
fn round_trip<T>(c: &Case) -> Value
where
    T: serde::de::DeserializeOwned + serde::Serialize,
{
    let parsed: T = serde_json::from_value(c.json.clone()).unwrap_or_else(|e| {
        panic!(
            "[{}] python JSON does not load into the rust type: {e}\n  {}",
            c.name, c.note
        )
    });
    serde_json::to_value(&parsed).expect("serialising the rust type cannot fail")
}

// -------------------------------------------------------------------------------------------
// 1) Round-trip parity over the whole corpus
// -------------------------------------------------------------------------------------------

/// Python's JSON → Rust type → JSON, for every case, compared key-set-first.
///
/// This is the load-bearing test. Every distinction the model draws — absent vs null vs value —
/// is only observable here, because a model that collapses two of those states still *parses*
/// the corpus fine and only betrays itself on the way back out.
#[test]
fn round_trip_matches_python_exactly() {
    let corpus = corpus();
    assert!(corpus.cases.len() >= 40, "corpus shrank — regenerate it");

    for c in &corpus.cases {
        let rust = match c.kind.as_str() {
            "position" => round_trip::<Position>(c),
            "position_internal" => {
                // `_spot_addr` is popped by the orchestrator before the response is built, so
                // the model must not carry it. Handled by its own test below.
                continue;
            }
            "spot" => round_trip::<SpotToken>(c),
            "chain" => round_trip::<ChainBucket>(c),
            "wallet" => round_trip::<Wallet>(c),
            "snapshot" => round_trip::<PortfolioSnapshot>(c),
            other => panic!("[{}] unknown corpus kind {other:?}", c.name),
        };
        assert_same(
            &format!("round-trip case `{}`", c.name),
            &c.note,
            &c.json,
            &rust,
        );
    }
}

/// `_spot_addr` must never reach the wire.
///
/// `_position` does store it (portfolio.py L217), but `_evm_chain_portfolio` pops it off every
/// position during spot dedup (L1903) *before* `_chain_result` runs, so no response can contain
/// it. The model keeps it as a non-serde field: parsing a pre-pop dict silently ignores the key,
/// and serialising never writes one.
#[test]
fn spot_addr_is_internal_and_never_serialised() {
    let c = corpus()
        .cases
        .into_iter()
        .find(|c| c.name == "position_spot_addr_prepop")
        .expect("corpus case missing");

    assert!(
        c.json.get("_spot_addr").is_some(),
        "the corpus case is supposed to be the PRE-pop dict — regenerate it"
    );

    let parsed: Position = serde_json::from_value(c.json.clone()).expect("must still parse");
    assert_eq!(
        parsed.spot_addr, None,
        "`_spot_addr` must not populate the internal field"
    );

    let rust = serde_json::to_value(&parsed).unwrap();
    assert!(
        rust.get("_spot_addr").is_none(),
        "`_spot_addr` leaked into the response"
    );

    // Everything else must survive untouched.
    let mut expected = c.json.clone();
    expected.as_object_mut().unwrap().remove("_spot_addr");
    assert_same("spot_addr stripped", &c.note, &expected, &rust);

    // And the post-pop twin — what actually ships — must be byte-identical to it.
    assert_same(
        "post-pop twin",
        &c.note,
        &case("position_spot_addr_postpop"),
        &rust,
    );
}

// -------------------------------------------------------------------------------------------
// 2) Rust-built structs vs Python's dicts
// -------------------------------------------------------------------------------------------
//
// The round-trip test proves the model can *carry* Python's shape. These prove it *produces*
// it: each struct is built the way a port's adapter would build it, with no reference to the
// corpus, and then compared against what the oracle emitted for the same inputs.

/// `_position(protocol, category, name, usd)` with nothing else: seven keys, `id`/`via` null,
/// `tokens` an empty array. A port that made `id`/`via` skip-if-none would emit five.
#[test]
fn builds_minimal_position() {
    let pos = Position::new(
        "Aave v3",
        "Borrowing",
        "Borrow vs. supplied collateral",
        Some(-1024.5),
    );
    assert_same(
        "position_minimal",
        "the seven keys `_position` always writes",
        &case("position_minimal"),
        &serde_json::to_value(&pos).unwrap(),
    );
}

/// `usd=None` serialises as `null`, not as an absent key — `types.ts` types it `number | null`
/// and the holdings table renders the row either way.
#[test]
fn builds_position_with_null_usd() {
    let pos = Position::new("Unknown", "Yield", "unpriced", None);
    assert_same(
        "position_usd_none",
        "usd is nullable, not optional",
        &case("position_usd_none"),
        &serde_json::to_value(&pos).unwrap(),
    );
}

/// `in_range=False` is falsy in Python but *not* `None`, so the key is written. A port that
/// tested truthiness instead of nullness would drop it and paint every LP as in-range.
#[test]
fn builds_position_with_false_in_range() {
    let mut pos = Position::new("Uniswap v3", "Liquidity Pool", "x", Some(1.0));
    pos.in_range = Some(false);
    assert_same(
        "position_in_range_false",
        "false is not absent",
        &case("position_in_range_false"),
        &serde_json::to_value(&pos).unwrap(),
    );

    // Same trap for a zero change: 0.0 is falsy, and a flat day must still report as flat.
    let mut flat = Position::new("Uniswap v3", "Liquidity Pool", "x", Some(1.0));
    flat.change24h = Some(Some(0.0));
    assert_same(
        "position_change24h_zero",
        "0.0 is not absent",
        &case("position_change24h_zero"),
        &serde_json::to_value(&flat).unwrap(),
    );
}

/// The three states of the `rewards` / `rewards_usd` pair, which share one Python statement.
#[test]
fn builds_the_three_reward_states() {
    let leg = TokenAmt {
        symbol: "AERO".into(),
        amount: 2.5,
        usd: Some(1.25),
        ..Default::default()
    };

    // (a) both present, both valued.
    let both = Position::new("Aerodrome", "Liquidity Pool", "x", Some(1.0))
        .with_rewards(vec![leg.clone()], Some(1.25));
    assert_same(
        "position_rewards_pair",
        "rewards + rewards_usd are written together",
        &case("position_rewards_pair"),
        &serde_json::to_value(&both).unwrap(),
    );

    // (b) rewards present, rewards_usd null — the key still exists.
    let null_usd =
        Position::new("Aerodrome", "Liquidity Pool", "x", Some(1.0)).with_rewards(vec![leg], None);
    assert_same(
        "position_rewards_usd_null",
        "rewards_usd is present-and-null, not absent",
        &case("position_rewards_usd_null"),
        &serde_json::to_value(&null_usd).unwrap(),
    );

    // (c) an orphan rewards_usd: Python discards it because the assignment is inside the
    //     `if rewards is not None` branch, so NEITHER key appears. The model makes the same
    //     shape unreachable through `with_rewards`, and the plain-struct spelling below is
    //     what a careless port would produce — it must not match.
    let orphan = Position::new("Aerodrome", "Liquidity Pool", "x", Some(1.0));
    assert_same(
        "position_rewards_usd_orphan",
        "an orphan rewards_usd is dropped entirely by the oracle",
        &case("position_rewards_usd_orphan"),
        &serde_json::to_value(&orphan).unwrap(),
    );

    let mut wrong = Position::new("Aerodrome", "Liquidity Pool", "x", Some(1.0));
    wrong.rewards_usd = Some(Some(99.0));
    let wrong = serde_json::to_value(&wrong).unwrap();
    let mut diffs = Vec::new();
    diff("", &case("position_rewards_usd_orphan"), &wrong, &mut diffs);
    assert_eq!(
        diffs.len(),
        1,
        "setting rewards_usd without rewards should be exactly one extra key: {diffs:?}"
    );
    assert!(
        matches!(diffs[0], Diff::ExtraKey(_)),
        "expected an extra-key diff: {diffs:?}"
    );
}

/// Every `_position` keyword at once, including a null health factor.
#[test]
fn builds_maximal_position() {
    let mut pos = Position::new(
        "Aerodrome",
        "Liquidity Pool",
        "WETH/USDC 0.05%",
        Some(4096.0),
    );
    pos.id = Some(Some("#99".into()));
    pos.via = Some("vfat.io".into());
    pos.tokens = vec![
        TokenAmt {
            symbol: "WETH".into(),
            amount: 1.0,
            usd: Some(2048.0),
            ..Default::default()
        },
        TokenAmt {
            symbol: "USDC".into(),
            amount: 2048.0,
            usd: Some(2048.0),
            ..Default::default()
        },
    ];
    pos.in_range = Some(true);
    pos = pos.with_rewards(
        vec![TokenAmt {
            symbol: "AERO".into(),
            amount: 10.0,
            usd: Some(5.0),
            ..Default::default()
        }],
        Some(5.0),
    );
    pos.change24h = Some(Some(1.25));
    pos.health = Some(LendingHealth {
        hf: Some(2.0),
        ltv: 0.25,
        liq_threshold: 0.8,
        collateral_usd: 1024.0,
        debt_usd: 256.0,
    });
    assert_same(
        "position_everything",
        "the maximal `_position` output",
        &case("position_everything"),
        &serde_json::to_value(&pos).unwrap(),
    );
}

/// Aave reports `u256::MAX` as the health factor when there is no debt; the oracle maps that
/// to `None`, so `hf` is null *inside* an otherwise fully populated object.
#[test]
fn builds_lending_health_with_null_hf() {
    let mut pos = Position::new("Aave v3", "Borrowing", "Supplied collateral", Some(0.0));
    pos.health = Some(LendingHealth {
        hf: None,
        ltv: 0.0,
        liq_threshold: 0.0,
        collateral_usd: 0.0,
        debt_usd: 0.0,
    });
    assert_same(
        "position_health_hf_null",
        "hf is null when there is no debt",
        &case("position_health_hf_null"),
        &serde_json::to_value(&pos).unwrap(),
    );
}

/// Lending legs carry `side` (supply/borrow); the compact health row groups by it.
#[test]
fn builds_lending_legs_with_side() {
    let mut pos = Position::new("Morpho", "Borrowing", "Borrow · WETH/USDC", Some(-128.0));
    pos.tokens = vec![
        TokenAmt {
            symbol: "WETH".into(),
            amount: 1.0,
            usd: Some(2048.0),
            side: Some("supply".into()),
            ..Default::default()
        },
        TokenAmt {
            symbol: "USDC".into(),
            amount: 128.0,
            usd: Some(128.0),
            side: Some("borrow".into()),
            ..Default::default()
        },
    ];
    pos.health = Some(LendingHealth {
        hf: Some(3.0),
        ltv: 0.0625,
        liq_threshold: 0.86,
        collateral_usd: 2048.0,
        debt_usd: 128.0,
    });
    assert_same(
        "position_lending_legs",
        "token legs carry a side",
        &case("position_lending_legs"),
        &serde_json::to_value(&pos).unwrap(),
    );
}

/// `range_pct` from vfat's `guaranteedAprPricePercentRange`: the branch is gated on
/// `widthPercent` alone, so `min`/`max` can be null while `width` is a number.
#[test]
fn builds_range_pct_with_null_bounds() {
    let py = case("vfat_meta_range_pct_null_bounds");
    let parsed: Position = serde_json::from_value(py.clone()).unwrap();
    let rng = parsed
        .range_pct
        .as_ref()
        .expect("range_pct must be present");
    assert_eq!(rng.min, None, "vfat returned a null minPricePercent");
    assert_eq!(rng.max, None, "vfat returned a null maxPricePercent");
    assert_eq!(rng.width, 12.5);

    let built = RangePct {
        min: None,
        max: None,
        width: 12.5,
    };
    assert_same(
        "range_pct null bounds",
        "min/max nullable, width required",
        &py["range_pct"],
        &serde_json::to_value(built).unwrap(),
    );
}

/// The whole lifecycle block written with null values: vfat returned actions with no
/// `blockTimestamp`/`actionType`, so five keys are present and null at once (and
/// `last_harvest_at` is absent, because the harvest filter matched nothing).
#[test]
fn builds_lifecycle_with_null_timestamps() {
    let py = case("vfat_lifecycle_null_timestamps");
    let parsed: Position = serde_json::from_value(py.clone()).unwrap();

    assert_eq!(
        parsed.deployed_at,
        Some(None),
        "present-and-null, not absent"
    );
    assert_eq!(parsed.updated_at, Some(None));
    assert_eq!(parsed.last_action, Some(None));
    assert_eq!(parsed.cycle_start, Some(None));
    assert_eq!(
        parsed.last_harvest_at, None,
        "never harvested -> key absent entirely"
    );

    assert_same(
        "lifecycle nulls",
        "null timestamps must survive as nulls",
        &py,
        &serde_json::to_value(&parsed).unwrap(),
    );
}

/// KuCoin bypasses `_position`, so its dicts have no `id` key at all and an extra `tier`.
#[test]
fn builds_kucoin_positions() {
    // Earn: change24h present-and-null for an unpriced currency — a shape `_position`
    // itself can never produce, because it only writes the key when the value is not None.
    let earn = Position {
        protocol: "KuCoin Earn".into(),
        category: "Yield".into(),
        name: "USDT savings".into(),
        id: None, // key omitted entirely, unlike every `_position` dict
        via: None,
        tokens: vec![TokenAmt {
            symbol: "USDT".into(),
            amount: 1024.0,
            usd: Some(1024.0),
            ..Default::default()
        }],
        usd: Some(1024.0),
        change24h: Some(None),
        apr: Some(5.25),
        tier: Some("cashflow".into()),
        ..Default::default()
    };
    assert_same(
        "kucoin_earn_null_change",
        "no id key, null change24h, extra tier",
        &case("kucoin_earn_null_change"),
        &serde_json::to_value(&earn).unwrap(),
    );

    // Futures bot: pnl on the position, and a BotInfo with count/margin/bots but no weights.
    let futures = Position {
        protocol: "KuCoin Futures Bot".into(),
        category: "Futures".into(),
        name: "2 AI futures bots".into(),
        id: None,
        via: None,
        tokens: vec![TokenAmt {
            symbol: "USDT".into(),
            amount: 2048.0,
            ..Default::default()
        }],
        usd: Some(2048.0),
        pnl_usd: Some(128.0),
        pnl_pct: Some(6.25),
        tier: Some("highrisk".into()),
        bot: Some(BotInfo {
            kind: "AI Futures".into(),
            status: "running".into(),
            count: Some(2),
            weights: None,
            margin_usd: Some(512.0),
            margin_pct: Some(25.0),
            bots: Some(vec![
                SubBot {
                    id: Some("robot123".into()),
                    usd: 1536.0,
                    pnl_usd: 96.0,
                    pnl_pct: 6.67,
                    margin: 384.0,
                },
                SubBot {
                    id: None,
                    usd: 512.0,
                    pnl_usd: 32.0,
                    pnl_pct: 6.67,
                    margin: 128.0,
                },
            ]),
        }),
        ..Default::default()
    };
    assert_same(
        "kucoin_futures_bot",
        "futures BotInfo: count/margin/bots, no weights; SubBot.id is nullable",
        &case("kucoin_futures_bot"),
        &serde_json::to_value(&futures).unwrap(),
    );

    // Spot bot: weights instead, and no count/margin/bots keys.
    let spot_bot = Position {
        protocol: "KuCoin Spot Bot".into(),
        category: "Rebalance".into(),
        name: "Smart Rebalance · 3 assets".into(),
        id: None,
        via: None,
        tokens: vec![
            TokenAmt {
                symbol: "BTC".into(),
                amount: 0.5,
                ..Default::default()
            },
            TokenAmt {
                symbol: "ETH".into(),
                amount: 2.0,
                ..Default::default()
            },
        ],
        usd: Some(4096.0),
        change24h: Some(Some(1.25)),
        tier: Some("cashflow".into()),
        bot: Some(BotInfo {
            kind: "Smart Rebalance".into(),
            status: "running".into(),
            count: None,
            weights: Some(vec![
                BotWeight {
                    symbol: "BTC".into(),
                    amount: 0.5,
                    usd: 3072.0,
                    pct: 75.0,
                },
                BotWeight {
                    symbol: "ETH".into(),
                    amount: 2.0,
                    usd: 1024.0,
                    pct: 25.0,
                },
            ]),
            margin_usd: None,
            margin_pct: None,
            bots: None,
        }),
        ..Default::default()
    };
    assert_same(
        "kucoin_spot_bot",
        "spot BotInfo: weights only",
        &case("kucoin_spot_bot"),
        &serde_json::to_value(&spot_bot).unwrap(),
    );
}

/// The six spot producers disagree about which keys exist; the model has to satisfy all of them.
#[test]
fn builds_every_spot_producer() {
    // EVM native: change24h + coin, no address.
    let native = SpotToken {
        symbol: Some("ETH".into()),
        amount: 1.5,
        price: Some(2048.0),
        usd: Some(3072.0),
        change24h: Some(Some(2.5)),
        coin: Some(Some("coingecko:ethereum".into())),
        kind: Some("native".into()),
        ..Default::default()
    };
    assert_same(
        "spot_evm_native",
        "EVM native coin",
        &case("spot_evm_native"),
        &serde_json::to_value(&native).unwrap(),
    );

    // Hyperliquid: change24h, coin and address keys are all ABSENT — not null.
    let hl = SpotToken {
        symbol: Some("HYPE".into()),
        amount: 100.0,
        price: Some(32.0),
        usd: Some(3200.0),
        kind: Some("token".into()),
        ..Default::default()
    };
    assert_same(
        "spot_hyperliquid",
        "no change24h/coin/address keys at all",
        &case("spot_hyperliquid"),
        &serde_json::to_value(&hl).unwrap(),
    );

    // A Blockscout token with no symbol and a chain with no DefiLlama prefix: symbol and coin
    // are both present-and-null. `types.ts` declares `symbol: string`.
    let anon = SpotToken {
        symbol: None,
        amount: 1.0,
        price: Some(2.0),
        usd: Some(2.0),
        change24h: Some(None),
        coin: Some(None),
        address: Some("0x0000000000000000000000000000000000000001".into()),
        kind: Some("token".into()),
        category: None,
    };
    assert_same(
        "spot_evm_token_null_symbol",
        "symbol and coin are nullable",
        &case("spot_evm_token_null_symbol"),
        &serde_json::to_value(&anon).unwrap(),
    );
}

/// `_chain_result` is exactly four keys, and `spot`/`defi` are `[]` rather than null when empty.
#[test]
fn builds_chain_bucket() {
    let bucket = ChainBucket {
        chain: "optimism".into(),
        usd: 0.5,
        spot: Vec::new(),
        defi: Vec::new(),
    };
    assert_same(
        "chain_result_empty",
        "empty lists, never null",
        &case("chain_result_empty"),
        &serde_json::to_value(&bucket).unwrap(),
    );
}

/// `_wallet` recomputes the total from its chains rather than trusting a passed-in figure.
#[test]
fn builds_wallet_totals_from_chains() {
    let py = case("wallet");
    let chains: Vec<ChainBucket> = serde_json::from_value(py["chains"].clone()).unwrap();
    let wallet = Wallet::new("0x7Fce9c293dBD6d050455B986cb6850114Aad71a8", chains);

    assert_eq!(wallet.total, 2048.25, "1792.0 + 256.25");
    assert_same(
        "wallet",
        "total is the sum of the buckets",
        &py,
        &serde_json::to_value(&wallet).unwrap(),
    );

    // A chain that came back below dust is dropped by `_chain_result` before `_wallet` sums,
    // so the dropped value must not appear in the total.
    let dropped = case("wallet_drops_none_chains");
    assert_eq!(
        dropped["total"].as_f64().unwrap(),
        2048.25,
        "the sub-dust chain must not be counted"
    );
    assert_eq!(
        dropped["chains"].as_array().unwrap().len(),
        2,
        "and must not be listed"
    );
}

/// The top-level envelope: six keys, `rates` always an object, both sentiment legs present.
#[test]
fn builds_snapshot_envelope() {
    // The degraded path — everything timed out.
    let degraded = PortfolioSnapshot::new(
        Vec::new(),
        Vec::new(),
        fallback_rates(),
        PortfolioSentiment::default(),
        1783924800.0,
    );
    assert_same(
        "snapshot_degraded",
        "rates falls back to an object; sentiment legs are null but present",
        &case("snapshot_degraded"),
        &serde_json::to_value(&degraded).unwrap(),
    );

    // The populated path, rebuilt around the corpus's own wallets.
    let py = case("snapshot_full");
    let wallets: Vec<Wallet> = serde_json::from_value(py["wallets"].clone()).unwrap();
    let rainbow: Rainbow = serde_json::from_value(py["sentiment"]["btc_rainbow"].clone()).unwrap();
    let full = PortfolioSnapshot::new(
        vec!["0x7Fce9c293dBD6d050455B986cb6850114Aad71a8".into()],
        wallets,
        Rates {
            usd: 1.0,
            thb: Some(32.5),
            btc_usd: Some(65536.0),
        },
        PortfolioSentiment {
            fear_greed: Some(FearGreed {
                value: 42,
                classification: "Fear".into(),
            }),
            btc_rainbow: Some(rainbow),
        },
        1783924800.5,
    );
    assert_eq!(full.total, 3072.25, "2048.25 (wallet) + 1024.0 (KuCoin)");
    assert_same(
        "snapshot_full",
        "the populated envelope",
        &py,
        &serde_json::to_value(&full).unwrap(),
    );

    // `addresses` lists only the requested wallets — the appended KuCoin wallet is not one.
    assert_eq!(py["addresses"].as_array().unwrap().len(), 1);
    assert_eq!(py["wallets"].as_array().unwrap().len(), 2);
    assert_eq!(py["wallets"][1]["address"], "KuCoin");
}

/// The portfolio envelope's `sentiment` has exactly two keys.
///
/// `market::Sentiment` (the `/api/sentiment` shape) also carries `mvrv_zscore`, `sopr`,
/// `puell` and `fetched_at`. Reusing it here would put four keys into every portfolio
/// response that `build_portfolios` never emits, which is why `PortfolioSentiment` exists.
#[test]
fn portfolio_sentiment_has_exactly_two_keys() {
    let value = serde_json::to_value(PortfolioSentiment::default()).unwrap();
    let keys: BTreeSet<&str> = value
        .as_object()
        .unwrap()
        .keys()
        .map(String::as_str)
        .collect();
    assert_eq!(keys, BTreeSet::from(["fear_greed", "btc_rainbow"]));
    assert_eq!(value, json!({"fear_greed": null, "btc_rainbow": null}));
}

/// A price band whose tick maths overflows: `fin()` nulls the non-finite bounds, so the keys
/// stay present with null values and `full` reports the position as unbounded.
#[test]
fn price_band_nulls_non_finite_bounds() {
    let py = case("price_band_full_range");
    let parsed: Position = serde_json::from_value(py.clone()).unwrap();
    let band: &PriceBand = parsed.price_band.as_ref().expect("band must be present");

    assert!(band.full, "a ±887272-tick range is effectively full-range");
    assert_eq!(band.base, "WETH");
    assert_eq!(band.quote, "USDC");
    for (name, v) in [
        ("lower", band.lower),
        ("upper", band.upper),
        ("cur", band.cur),
    ] {
        assert!(
            v.is_none_or(f64::is_finite),
            "{name} must be null or finite — `fin()` never lets an inf through"
        );
    }
    assert_same(
        "price_band",
        &py.to_string(),
        &py,
        &serde_json::to_value(&parsed).unwrap(),
    );
}
