//! Differential parity for the spam filter, against the Python oracle.
//!
//! `spam_corpus.json` is generated by running `portfolio._is_spam` over 3,255 combinations of
//! symbol × name × reputation — real tickers, known scam shapes, word-boundary near-misses
//! (`ratio` vs `.io`, `organic` vs `.org`, `proclaim` vs `claim`), emoji bait, and every
//! reputation label. Regenerate with the snippet in `docs/parity.md` if the Python changes.
//!
//! This is the cheap half of Phase 3 parity: pure functions can be compared exhaustively offline,
//! with no chain access and no flakiness.

use serde::Deserialize;

use lyra_chain::spam::{MIN_CONFIDENCE, TokenInfo, is_spam};

#[derive(Debug, Deserialize)]
struct Corpus {
    min_confidence: f64,
    cases: Vec<Case>,
}

#[derive(Debug, Deserialize)]
struct Case {
    symbol: String,
    name: String,
    reputation: Option<String>,
    spam: bool,
}

fn load() -> Corpus {
    let raw = include_str!("spam_corpus.json");
    serde_json::from_str(raw).expect("spam_corpus.json should parse")
}

#[test]
fn the_confidence_threshold_matches_python() {
    assert_eq!(load().min_confidence, MIN_CONFIDENCE);
}

#[test]
fn the_spam_filter_agrees_with_python_on_every_case() {
    let corpus = load();
    assert!(
        corpus.cases.len() > 3000,
        "corpus looks truncated: {}",
        corpus.cases.len()
    );

    let mut disagreements = Vec::new();
    for case in &corpus.cases {
        let token = TokenInfo {
            symbol: Some(case.symbol.as_str()),
            name: Some(case.name.as_str()),
            reputation: case.reputation.as_deref(),
        };
        let ours = is_spam(&token);
        if ours != case.spam {
            disagreements.push(format!(
                "symbol={:?} name={:?} reputation={:?} — python={} rust={}",
                case.symbol, case.name, case.reputation, case.spam, ours
            ));
        }
    }

    assert!(
        disagreements.is_empty(),
        "{} of {} cases disagree:\n{}",
        disagreements.len(),
        corpus.cases.len(),
        disagreements
            .iter()
            .take(20)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

#[test]
fn the_corpus_covers_both_verdicts() {
    // A corpus that was all-spam or all-clean would pass trivially while testing nothing.
    let corpus = load();
    let spam = corpus.cases.iter().filter(|c| c.spam).count();
    let clean = corpus.cases.len() - spam;
    assert!(
        spam > 100 && clean > 100,
        "unbalanced corpus: {spam} spam / {clean} clean"
    );
}
